[versions]
#noinspection AndroidGradlePluginVersion
agp = "8.12.1"
#noinspection NewerVersionAvailable
kotlin = "2.2.0"
googleKsp = "2.2.0-2.0.2"
coreKtx = "1.17.0"
#noinspection GradleDependency
lifecycleRuntimeKtx = "2.9.2"
activityCompose = "1.11.0"
#noinspection GradleDependency
composeBom = "2025.08.00"
composeNavigation = "2.9.4"
#noinspection NewerVersionAvailable
koin = "4.1.0"
room = "2.8.0"
#noinspection NewerVersionAvailable
ktor = "3.2.3"
datastore = "1.1.7"
materialIcons = "1.7.8"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
composeIcons = "1.1.1"
coil="2.7.0"
lottie-compose = "6.6.9"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "composeNavigation" }

koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-androidx-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin" }

androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }

ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-serialization = { group = "io.ktor", name = "ktor-client-serialization", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }

androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

androidx-material-icons = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "materialIcons" }
compose-simple-icons = { group = "br.com.devsrsouza.compose.icons", name = "simple-icons", version.ref = "composeIcons" }
compose-eva-icons = { group = "br.com.devsrsouza.compose.icons", name = "eva-icons", version.ref = "composeIcons" }
compose-coil = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie-compose" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
org-jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "googleKsp" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
org-jetbrains-kotlin-plugin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

[bundles]
compose = [
    "androidx-ui",
    "androidx-ui-graphics",
    "androidx-ui-tooling-preview",
    "androidx-material3",
    "compose-coil"
]

koin = [
    "koin-android",
    "koin-androidx-compose"
]

room = [
    "androidx-room-runtime",
    "androidx-room-ktx"
]

ktor = [
    "ktor-client-core",
    "ktor-client-okhttp",
    "ktor-client-serialization",
    "ktor-client-logging",
    "ktor-serialization-kotlinx-json",
    "ktor-client-content-negotiation"
]

icons = [
    "androidx-material-icons",
    "compose-simple-icons",
    "compose-eva-icons"
]

animation = [
    "lottie-compose"
]

testing-unit = [
    "junit"
]

testing-android = [
    "androidx-junit",
    "androidx-espresso-core"
]